/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooteBar: typeof import('./src/components/default/AppFooteBar.vue')['default']
    AppHeadBar: typeof import('./src/components/default/AppHeadBar.vue')['default']
    AppHeaderBar: typeof import('./src/components/default/AppHeaderBar.vue')['default']
    AppSideBar: typeof import('./src/components/default/AppSideBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NovaConsulta: typeof import('./src/components/NovaConsulta.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
